### ISSUE TITLE
prawcore.exceptions.ResponseException: received 401 HTTP response

### ISSUE THREAD

**Issue by ohhdemgirls** [minibug1021/redditAccountArchiver#1]
Use: `python3 archiver.py 'minibug'`

```
Generating comment database...
Creating ID list for new...
Traceback (most recent call last):
  File "archiver.py", line 25, in <module>
    for comment in user.comments.new(limit=1000):
  File "/usr/local/lib/python3.5/dist-packages/praw/models/listing/generator.py", line 52, in __next__
    self._next_batch()
  File "/usr/local/lib/python3.5/dist-packages/praw/models/listing/generator.py", line 62, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/usr/local/lib/python3.5/dist-packages/praw/reddit.py", line 367, in get
    data = self.request('GET', path, params=params)
  File "/usr/local/lib/python3.5/dist-packages/praw/reddit.py", line 472, in request
    params=params)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/sessions.py", line 175, in request
    params=params, url=url)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/sessions.py", line 109, in _request_with_retries
    data, files, json, method, params, retries, url)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/sessions.py", line 94, in _make_request
    params=params)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/rate_limit.py", line 32, in call
    kwargs['headers'] = set_header_callback()
  File "/usr/local/lib/python3.5/dist-packages/prawcore/sessions.py", line 135, in _set_header_callback
    self._authorizer.refresh()
  File "/usr/local/lib/python3.5/dist-packages/prawcore/auth.py", line 256, in refresh
    device_id=self._device_id)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/auth.py", line 138, in _request_token
    response = self._authenticator._post(url, **data)
  File "/usr/local/lib/python3.5/dist-packages/prawcore/auth.py", line 31, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
```

**Comment by ohhdemgirls** [comment]
Scrap that, didn't realise praw now requires authentication. I've just started ripping 28k accounts, will let you know how I get on.

**Comment by ohhdemgirls** [comment]
Scrap that, I didn't realise praw required authentication now.
